language: node_js
node_js:
- '5.4.1'
sudo: false
cache:
  directories:
  - node_modules
before_install:
- export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
- npm config set spin false
- npm install -g npm@^2
- npm install -g jshint@^2.5
install:
- npm install -g bower
- npm install -g ember-cli@1.13.13
- npm install frost-components/frost-css
- npm install frost-components/frost-button
- npm install frost-components/frost-tabs
- npm install frost-components/frost-link
- npm install frost-components/frost-scroll
- npm install frost-components/frost-svg
- npm install frost-components/frost-text

after_success:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- .travis/push.sh

notifications:
  email: false

matrix:
  fast_finish: true
  allow_failures:
  - node_js: iojs
