---
language: node_js
node_js:
  - "0.12"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"
  - "npm install -g jshint@^2.5"

install:
  - npm install -g bower
  # - npm install
  - bower install
  
  #content generation scripts dependancies
  - npm install chalk
  - npm install path
  - npm install bower
  - npm install sync-request
  - npm install npm

script:
  # - npm test
  - node generate-pages-from-markdown.js
  - node generate-components.js

notifications:
    email: false
matrix:
    fast_finish: true
    allow_failures:
        - node_js: "iojs"
